//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftObject.TrainConcept.TCLocalServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://webtrain.softobject.at/webservice", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WTSpotItem", Namespace="http://webtrain.softobject.at/webservice")]
    [System.SerializableAttribute()]
    public partial class WTSpotItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WTSpotNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSIDNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSIDPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string WTSpotName {
            get {
                return this.WTSpotNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WTSpotNameField, value) != true)) {
                    this.WTSpotNameField = value;
                    this.RaisePropertyChanged("WTSpotName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IPAddress {
            get {
                return this.IPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAddressField, value) != true)) {
                    this.IPAddressField = value;
                    this.RaisePropertyChanged("IPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SSIDName {
            get {
                return this.SSIDNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SSIDNameField, value) != true)) {
                    this.SSIDNameField = value;
                    this.RaisePropertyChanged("SSIDName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SSIDPassword {
            get {
                return this.SSIDPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.SSIDPasswordField, value) != true)) {
                    this.SSIDPasswordField = value;
                    this.RaisePropertyChanged("SSIDPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webtrain.softobject.at/webservice", ConfigurationName="TCLocalServiceReference1.QueryUpdateSoap")]
    public interface QueryUpdateSoap {
        
        // CODEGEN: Generating message contract since element name strVersion from namespace http://webtrain.softobject.at/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/UpdateAvailable", ReplyAction="*")]
        SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableResponse UpdateAvailable(SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/UpdateAvailable", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableResponse> UpdateAvailableAsync(SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableRequest request);
        
        // CODEGEN: Generating message contract since element name GetServerIPAddressResult from namespace http://webtrain.softobject.at/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetServerIPAddress", ReplyAction="*")]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressResponse GetServerIPAddress(SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetServerIPAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressResponse> GetServerIPAddressAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressRequest request);
        
        // CODEGEN: Generating message contract since element name strIPAdress from namespace http://webtrain.softobject.at/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetLicenseIdByServerIPAddress", ReplyAction="*")]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressResponse GetLicenseIdByServerIPAddress(SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetLicenseIdByServerIPAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressResponse> GetLicenseIdByServerIPAddressAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressRequest request);
        
        // CODEGEN: Generating message contract since element name strIPAddress from namespace http://webtrain.softobject.at/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/SetServerIPAddress", ReplyAction="*")]
        SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressResponse SetServerIPAddress(SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/SetServerIPAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressResponse> SetServerIPAddressAsync(SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressRequest request);
        
        // CODEGEN: Generating message contract since element name filename from namespace http://webtrain.softobject.at/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetFile", ReplyAction="*")]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetFileResponse GetFile(SoftObject.TrainConcept.TCLocalServiceReference1.GetFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetFile", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetFileResponse> GetFileAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetFileRequest request);
        
        // CODEGEN: Generating message contract since element name buffer from namespace http://webtrain.softobject.at/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/PutFile", ReplyAction="*")]
        SoftObject.TrainConcept.TCLocalServiceReference1.PutFileResponse PutFile(SoftObject.TrainConcept.TCLocalServiceReference1.PutFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/PutFile", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.PutFileResponse> PutFileAsync(SoftObject.TrainConcept.TCLocalServiceReference1.PutFileRequest request);
        
        // CODEGEN: Generating message contract since element name GetCustomerListResult from namespace http://webtrain.softobject.at/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetCustomerList", ReplyAction="*")]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListResponse GetCustomerList(SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetCustomerList", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListResponse> GetCustomerListAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserListResult from namespace http://webtrain.softobject.at/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetUserList", ReplyAction="*")]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListResponse GetUserList(SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetUserList", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListResponse> GetUserListAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListRequest request);
        
        // CODEGEN: Generating message contract since element name strUsername from namespace http://webtrain.softobject.at/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/SetUserPassword", ReplyAction="*")]
        SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordResponse SetUserPassword(SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/SetUserPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordResponse> SetUserPasswordAsync(SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name strUsername from namespace http://webtrain.softobject.at/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetPackagesToLaunch", ReplyAction="*")]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchResponse GetPackagesToLaunch(SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetPackagesToLaunch", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchResponse> GetPackagesToLaunchAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchRequest request);
        
        // CODEGEN: Generating message contract since element name GetAdminInformationResult from namespace http://webtrain.softobject.at/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetAdminInformation", ReplyAction="*")]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationResponse GetAdminInformation(SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetAdminInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationResponse> GetAdminInformationAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationRequest request);
        
        // CODEGEN: Generating message contract since element name GetSpotItemsResult from namespace http://webtrain.softobject.at/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetSpotItems", ReplyAction="*")]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsResponse GetSpotItems(SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetSpotItems", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsResponse> GetSpotItemsAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsRequest request);
        
        // CODEGEN: Generating message contract since element name GetLearnmapsToTransferResult from namespace http://webtrain.softobject.at/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetLearnmapsToTransfer", ReplyAction="*")]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferResponse GetLearnmapsToTransfer(SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webtrain.softobject.at/webservice/GetLearnmapsToTransfer", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferResponse> GetLearnmapsToTransferAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAvailableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAvailable", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableRequestBody Body;
        
        public UpdateAvailableRequest() {
        }
        
        public UpdateAvailableRequest(SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class UpdateAvailableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strVersion;
        
        public UpdateAvailableRequestBody() {
        }
        
        public UpdateAvailableRequestBody(string strVersion) {
            this.strVersion = strVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAvailableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAvailableResponse", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableResponseBody Body;
        
        public UpdateAvailableResponse() {
        }
        
        public UpdateAvailableResponse(SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class UpdateAvailableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateAvailableResult;
        
        public UpdateAvailableResponseBody() {
        }
        
        public UpdateAvailableResponseBody(string UpdateAvailableResult) {
            this.UpdateAvailableResult = UpdateAvailableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServerIPAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServerIPAddress", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressRequestBody Body;
        
        public GetServerIPAddressRequest() {
        }
        
        public GetServerIPAddressRequest(SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class GetServerIPAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int iLicenseId;
        
        public GetServerIPAddressRequestBody() {
        }
        
        public GetServerIPAddressRequestBody(int iLicenseId) {
            this.iLicenseId = iLicenseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServerIPAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServerIPAddressResponse", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressResponseBody Body;
        
        public GetServerIPAddressResponse() {
        }
        
        public GetServerIPAddressResponse(SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class GetServerIPAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetServerIPAddressResult;
        
        public GetServerIPAddressResponseBody() {
        }
        
        public GetServerIPAddressResponseBody(string GetServerIPAddressResult) {
            this.GetServerIPAddressResult = GetServerIPAddressResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLicenseIdByServerIPAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLicenseIdByServerIPAddress", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressRequestBody Body;
        
        public GetLicenseIdByServerIPAddressRequest() {
        }
        
        public GetLicenseIdByServerIPAddressRequest(SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class GetLicenseIdByServerIPAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strIPAdress;
        
        public GetLicenseIdByServerIPAddressRequestBody() {
        }
        
        public GetLicenseIdByServerIPAddressRequestBody(string strIPAdress) {
            this.strIPAdress = strIPAdress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLicenseIdByServerIPAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLicenseIdByServerIPAddressResponse", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressResponseBody Body;
        
        public GetLicenseIdByServerIPAddressResponse() {
        }
        
        public GetLicenseIdByServerIPAddressResponse(SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class GetLicenseIdByServerIPAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetLicenseIdByServerIPAddressResult;
        
        public GetLicenseIdByServerIPAddressResponseBody() {
        }
        
        public GetLicenseIdByServerIPAddressResponseBody(int GetLicenseIdByServerIPAddressResult) {
            this.GetLicenseIdByServerIPAddressResult = GetLicenseIdByServerIPAddressResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetServerIPAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetServerIPAddress", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressRequestBody Body;
        
        public SetServerIPAddressRequest() {
        }
        
        public SetServerIPAddressRequest(SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class SetServerIPAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int iLicenseId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strIPAddress;
        
        public SetServerIPAddressRequestBody() {
        }
        
        public SetServerIPAddressRequestBody(int iLicenseId, string strIPAddress) {
            this.iLicenseId = iLicenseId;
            this.strIPAddress = strIPAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetServerIPAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetServerIPAddressResponse", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressResponseBody Body;
        
        public SetServerIPAddressResponse() {
        }
        
        public SetServerIPAddressResponse(SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class SetServerIPAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetServerIPAddressResult;
        
        public SetServerIPAddressResponseBody() {
        }
        
        public SetServerIPAddressResponseBody(bool SetServerIPAddressResult) {
            this.SetServerIPAddressResult = SetServerIPAddressResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFile", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetFileRequestBody Body;
        
        public GetFileRequest() {
        }
        
        public GetFileRequest(SoftObject.TrainConcept.TCLocalServiceReference1.GetFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class GetFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        public GetFileRequestBody() {
        }
        
        public GetFileRequestBody(string filename) {
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileResponse", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetFileResponseBody Body;
        
        public GetFileResponse() {
        }
        
        public GetFileResponse(SoftObject.TrainConcept.TCLocalServiceReference1.GetFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class GetFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileResult;
        
        public GetFileResponseBody() {
        }
        
        public GetFileResponseBody(byte[] GetFileResult) {
            this.GetFileResult = GetFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFile", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.PutFileRequestBody Body;
        
        public PutFileRequest() {
        }
        
        public PutFileRequest(SoftObject.TrainConcept.TCLocalServiceReference1.PutFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class PutFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int licenseId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] buffer;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int iPackageId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int iMaxPackages;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string filename;
        
        public PutFileRequestBody() {
        }
        
        public PutFileRequestBody(int licenseId, byte[] buffer, int iPackageId, int iMaxPackages, string filename) {
            this.licenseId = licenseId;
            this.buffer = buffer;
            this.iPackageId = iPackageId;
            this.iMaxPackages = iMaxPackages;
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFileResponse", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.PutFileResponseBody Body;
        
        public PutFileResponse() {
        }
        
        public PutFileResponse(SoftObject.TrainConcept.TCLocalServiceReference1.PutFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PutFileResponseBody {
        
        public PutFileResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerList", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListRequestBody Body;
        
        public GetCustomerListRequest() {
        }
        
        public GetCustomerListRequest(SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCustomerListRequestBody {
        
        public GetCustomerListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerListResponse", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListResponseBody Body;
        
        public GetCustomerListResponse() {
        }
        
        public GetCustomerListResponse(SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class GetCustomerListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.ArrayOfString GetCustomerListResult;
        
        public GetCustomerListResponseBody() {
        }
        
        public GetCustomerListResponseBody(SoftObject.TrainConcept.TCLocalServiceReference1.ArrayOfString GetCustomerListResult) {
            this.GetCustomerListResult = GetCustomerListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserList", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListRequestBody Body;
        
        public GetUserListRequest() {
        }
        
        public GetUserListRequest(SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class GetUserListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int iLicenseId;
        
        public GetUserListRequestBody() {
        }
        
        public GetUserListRequestBody(int iLicenseId) {
            this.iLicenseId = iLicenseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserListResponse", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListResponseBody Body;
        
        public GetUserListResponse() {
        }
        
        public GetUserListResponse(SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class GetUserListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.ArrayOfString GetUserListResult;
        
        public GetUserListResponseBody() {
        }
        
        public GetUserListResponseBody(SoftObject.TrainConcept.TCLocalServiceReference1.ArrayOfString GetUserListResult) {
            this.GetUserListResult = GetUserListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetUserPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetUserPassword", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordRequestBody Body;
        
        public SetUserPasswordRequest() {
        }
        
        public SetUserPasswordRequest(SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class SetUserPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int iLicenseId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strPassword;
        
        public SetUserPasswordRequestBody() {
        }
        
        public SetUserPasswordRequestBody(int iLicenseId, string strUsername, string strPassword) {
            this.iLicenseId = iLicenseId;
            this.strUsername = strUsername;
            this.strPassword = strPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetUserPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetUserPasswordResponse", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordResponseBody Body;
        
        public SetUserPasswordResponse() {
        }
        
        public SetUserPasswordResponse(SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class SetUserPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetUserPasswordResult;
        
        public SetUserPasswordResponseBody() {
        }
        
        public SetUserPasswordResponseBody(bool SetUserPasswordResult) {
            this.SetUserPasswordResult = SetUserPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPackagesToLaunchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPackagesToLaunch", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchRequestBody Body;
        
        public GetPackagesToLaunchRequest() {
        }
        
        public GetPackagesToLaunchRequest(SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class GetPackagesToLaunchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int iLicenseId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strUsername;
        
        public GetPackagesToLaunchRequestBody() {
        }
        
        public GetPackagesToLaunchRequestBody(int iLicenseId, string strUsername) {
            this.iLicenseId = iLicenseId;
            this.strUsername = strUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPackagesToLaunchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPackagesToLaunchResponse", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchResponseBody Body;
        
        public GetPackagesToLaunchResponse() {
        }
        
        public GetPackagesToLaunchResponse(SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class GetPackagesToLaunchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.ArrayOfString GetPackagesToLaunchResult;
        
        public GetPackagesToLaunchResponseBody() {
        }
        
        public GetPackagesToLaunchResponseBody(SoftObject.TrainConcept.TCLocalServiceReference1.ArrayOfString GetPackagesToLaunchResult) {
            this.GetPackagesToLaunchResult = GetPackagesToLaunchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdminInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAdminInformation", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationRequestBody Body;
        
        public GetAdminInformationRequest() {
        }
        
        public GetAdminInformationRequest(SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class GetAdminInformationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int iLicenseId;
        
        public GetAdminInformationRequestBody() {
        }
        
        public GetAdminInformationRequestBody(int iLicenseId) {
            this.iLicenseId = iLicenseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdminInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAdminInformationResponse", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationResponseBody Body;
        
        public GetAdminInformationResponse() {
        }
        
        public GetAdminInformationResponse(SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class GetAdminInformationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAdminInformationResult;
        
        public GetAdminInformationResponseBody() {
        }
        
        public GetAdminInformationResponseBody(string GetAdminInformationResult) {
            this.GetAdminInformationResult = GetAdminInformationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpotItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpotItems", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsRequestBody Body;
        
        public GetSpotItemsRequest() {
        }
        
        public GetSpotItemsRequest(SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSpotItemsRequestBody {
        
        public GetSpotItemsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSpotItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSpotItemsResponse", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsResponseBody Body;
        
        public GetSpotItemsResponse() {
        }
        
        public GetSpotItemsResponse(SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class GetSpotItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.WTSpotItem[] GetSpotItemsResult;
        
        public GetSpotItemsResponseBody() {
        }
        
        public GetSpotItemsResponseBody(SoftObject.TrainConcept.TCLocalServiceReference1.WTSpotItem[] GetSpotItemsResult) {
            this.GetSpotItemsResult = GetSpotItemsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLearnmapsToTransferRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLearnmapsToTransfer", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferRequestBody Body;
        
        public GetLearnmapsToTransferRequest() {
        }
        
        public GetLearnmapsToTransferRequest(SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class GetLearnmapsToTransferRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int iLicenseId;
        
        public GetLearnmapsToTransferRequestBody() {
        }
        
        public GetLearnmapsToTransferRequestBody(int iLicenseId) {
            this.iLicenseId = iLicenseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLearnmapsToTransferResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLearnmapsToTransferResponse", Namespace="http://webtrain.softobject.at/webservice", Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferResponseBody Body;
        
        public GetLearnmapsToTransferResponse() {
        }
        
        public GetLearnmapsToTransferResponse(SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webtrain.softobject.at/webservice")]
    public partial class GetLearnmapsToTransferResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoftObject.TrainConcept.TCLocalServiceReference1.ArrayOfString GetLearnmapsToTransferResult;
        
        public GetLearnmapsToTransferResponseBody() {
        }
        
        public GetLearnmapsToTransferResponseBody(SoftObject.TrainConcept.TCLocalServiceReference1.ArrayOfString GetLearnmapsToTransferResult) {
            this.GetLearnmapsToTransferResult = GetLearnmapsToTransferResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryUpdateSoapChannel : SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryUpdateSoapClient : System.ServiceModel.ClientBase<SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap>, SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap {
        
        public QueryUpdateSoapClient() {
        }
        
        public QueryUpdateSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryUpdateSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryUpdateSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryUpdateSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableResponse SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.UpdateAvailable(SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableRequest request) {
            return base.Channel.UpdateAvailable(request);
        }
        
        public string UpdateAvailable(string strVersion) {
            SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableRequestBody();
            inValue.Body.strVersion = strVersion;
            SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableResponse retVal = ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).UpdateAvailable(inValue);
            return retVal.Body.UpdateAvailableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableResponse> SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.UpdateAvailableAsync(SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableRequest request) {
            return base.Channel.UpdateAvailableAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableResponse> UpdateAvailableAsync(string strVersion) {
            SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.UpdateAvailableRequestBody();
            inValue.Body.strVersion = strVersion;
            return ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).UpdateAvailableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressResponse SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetServerIPAddress(SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressRequest request) {
            return base.Channel.GetServerIPAddress(request);
        }
        
        public string GetServerIPAddress(int iLicenseId) {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressRequestBody();
            inValue.Body.iLicenseId = iLicenseId;
            SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressResponse retVal = ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetServerIPAddress(inValue);
            return retVal.Body.GetServerIPAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressResponse> SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetServerIPAddressAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressRequest request) {
            return base.Channel.GetServerIPAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressResponse> GetServerIPAddressAsync(int iLicenseId) {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetServerIPAddressRequestBody();
            inValue.Body.iLicenseId = iLicenseId;
            return ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetServerIPAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressResponse SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetLicenseIdByServerIPAddress(SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressRequest request) {
            return base.Channel.GetLicenseIdByServerIPAddress(request);
        }
        
        public int GetLicenseIdByServerIPAddress(string strIPAdress) {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressRequestBody();
            inValue.Body.strIPAdress = strIPAdress;
            SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressResponse retVal = ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetLicenseIdByServerIPAddress(inValue);
            return retVal.Body.GetLicenseIdByServerIPAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressResponse> SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetLicenseIdByServerIPAddressAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressRequest request) {
            return base.Channel.GetLicenseIdByServerIPAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressResponse> GetLicenseIdByServerIPAddressAsync(string strIPAdress) {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetLicenseIdByServerIPAddressRequestBody();
            inValue.Body.strIPAdress = strIPAdress;
            return ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetLicenseIdByServerIPAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressResponse SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.SetServerIPAddress(SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressRequest request) {
            return base.Channel.SetServerIPAddress(request);
        }
        
        public bool SetServerIPAddress(int iLicenseId, string strIPAddress) {
            SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressRequestBody();
            inValue.Body.iLicenseId = iLicenseId;
            inValue.Body.strIPAddress = strIPAddress;
            SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressResponse retVal = ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).SetServerIPAddress(inValue);
            return retVal.Body.SetServerIPAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressResponse> SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.SetServerIPAddressAsync(SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressRequest request) {
            return base.Channel.SetServerIPAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressResponse> SetServerIPAddressAsync(int iLicenseId, string strIPAddress) {
            SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.SetServerIPAddressRequestBody();
            inValue.Body.iLicenseId = iLicenseId;
            inValue.Body.strIPAddress = strIPAddress;
            return ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).SetServerIPAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetFileResponse SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetFile(SoftObject.TrainConcept.TCLocalServiceReference1.GetFileRequest request) {
            return base.Channel.GetFile(request);
        }
        
        public byte[] GetFile(string filename) {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetFileRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetFileRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetFileRequestBody();
            inValue.Body.filename = filename;
            SoftObject.TrainConcept.TCLocalServiceReference1.GetFileResponse retVal = ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetFile(inValue);
            return retVal.Body.GetFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetFileResponse> SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetFileAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetFileRequest request) {
            return base.Channel.GetFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetFileResponse> GetFileAsync(string filename) {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetFileRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetFileRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetFileRequestBody();
            inValue.Body.filename = filename;
            return ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftObject.TrainConcept.TCLocalServiceReference1.PutFileResponse SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.PutFile(SoftObject.TrainConcept.TCLocalServiceReference1.PutFileRequest request) {
            return base.Channel.PutFile(request);
        }
        
        public void PutFile(int licenseId, byte[] buffer, int iPackageId, int iMaxPackages, string filename) {
            SoftObject.TrainConcept.TCLocalServiceReference1.PutFileRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.PutFileRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.PutFileRequestBody();
            inValue.Body.licenseId = licenseId;
            inValue.Body.buffer = buffer;
            inValue.Body.iPackageId = iPackageId;
            inValue.Body.iMaxPackages = iMaxPackages;
            inValue.Body.filename = filename;
            SoftObject.TrainConcept.TCLocalServiceReference1.PutFileResponse retVal = ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).PutFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.PutFileResponse> SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.PutFileAsync(SoftObject.TrainConcept.TCLocalServiceReference1.PutFileRequest request) {
            return base.Channel.PutFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.PutFileResponse> PutFileAsync(int licenseId, byte[] buffer, int iPackageId, int iMaxPackages, string filename) {
            SoftObject.TrainConcept.TCLocalServiceReference1.PutFileRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.PutFileRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.PutFileRequestBody();
            inValue.Body.licenseId = licenseId;
            inValue.Body.buffer = buffer;
            inValue.Body.iPackageId = iPackageId;
            inValue.Body.iMaxPackages = iMaxPackages;
            inValue.Body.filename = filename;
            return ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).PutFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListResponse SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetCustomerList(SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListRequest request) {
            return base.Channel.GetCustomerList(request);
        }
        
        public SoftObject.TrainConcept.TCLocalServiceReference1.ArrayOfString GetCustomerList() {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListRequestBody();
            SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListResponse retVal = ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetCustomerList(inValue);
            return retVal.Body.GetCustomerListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListResponse> SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetCustomerListAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListRequest request) {
            return base.Channel.GetCustomerListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListResponse> GetCustomerListAsync() {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetCustomerListRequestBody();
            return ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetCustomerListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListResponse SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetUserList(SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListRequest request) {
            return base.Channel.GetUserList(request);
        }
        
        public SoftObject.TrainConcept.TCLocalServiceReference1.ArrayOfString GetUserList(int iLicenseId) {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListRequestBody();
            inValue.Body.iLicenseId = iLicenseId;
            SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListResponse retVal = ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetUserList(inValue);
            return retVal.Body.GetUserListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListResponse> SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetUserListAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListRequest request) {
            return base.Channel.GetUserListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListResponse> GetUserListAsync(int iLicenseId) {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetUserListRequestBody();
            inValue.Body.iLicenseId = iLicenseId;
            return ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetUserListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordResponse SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.SetUserPassword(SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordRequest request) {
            return base.Channel.SetUserPassword(request);
        }
        
        public bool SetUserPassword(int iLicenseId, string strUsername, string strPassword) {
            SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordRequestBody();
            inValue.Body.iLicenseId = iLicenseId;
            inValue.Body.strUsername = strUsername;
            inValue.Body.strPassword = strPassword;
            SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordResponse retVal = ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).SetUserPassword(inValue);
            return retVal.Body.SetUserPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordResponse> SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.SetUserPasswordAsync(SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordRequest request) {
            return base.Channel.SetUserPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordResponse> SetUserPasswordAsync(int iLicenseId, string strUsername, string strPassword) {
            SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.SetUserPasswordRequestBody();
            inValue.Body.iLicenseId = iLicenseId;
            inValue.Body.strUsername = strUsername;
            inValue.Body.strPassword = strPassword;
            return ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).SetUserPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchResponse SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetPackagesToLaunch(SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchRequest request) {
            return base.Channel.GetPackagesToLaunch(request);
        }
        
        public SoftObject.TrainConcept.TCLocalServiceReference1.ArrayOfString GetPackagesToLaunch(int iLicenseId, string strUsername) {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchRequestBody();
            inValue.Body.iLicenseId = iLicenseId;
            inValue.Body.strUsername = strUsername;
            SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchResponse retVal = ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetPackagesToLaunch(inValue);
            return retVal.Body.GetPackagesToLaunchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchResponse> SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetPackagesToLaunchAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchRequest request) {
            return base.Channel.GetPackagesToLaunchAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchResponse> GetPackagesToLaunchAsync(int iLicenseId, string strUsername) {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetPackagesToLaunchRequestBody();
            inValue.Body.iLicenseId = iLicenseId;
            inValue.Body.strUsername = strUsername;
            return ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetPackagesToLaunchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationResponse SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetAdminInformation(SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationRequest request) {
            return base.Channel.GetAdminInformation(request);
        }
        
        public string GetAdminInformation(int iLicenseId) {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationRequestBody();
            inValue.Body.iLicenseId = iLicenseId;
            SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationResponse retVal = ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetAdminInformation(inValue);
            return retVal.Body.GetAdminInformationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationResponse> SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetAdminInformationAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationRequest request) {
            return base.Channel.GetAdminInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationResponse> GetAdminInformationAsync(int iLicenseId) {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetAdminInformationRequestBody();
            inValue.Body.iLicenseId = iLicenseId;
            return ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetAdminInformationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsResponse SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetSpotItems(SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsRequest request) {
            return base.Channel.GetSpotItems(request);
        }
        
        public SoftObject.TrainConcept.TCLocalServiceReference1.WTSpotItem[] GetSpotItems() {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsRequestBody();
            SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsResponse retVal = ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetSpotItems(inValue);
            return retVal.Body.GetSpotItemsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsResponse> SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetSpotItemsAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsRequest request) {
            return base.Channel.GetSpotItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsResponse> GetSpotItemsAsync() {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetSpotItemsRequestBody();
            return ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetSpotItemsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferResponse SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetLearnmapsToTransfer(SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferRequest request) {
            return base.Channel.GetLearnmapsToTransfer(request);
        }
        
        public SoftObject.TrainConcept.TCLocalServiceReference1.ArrayOfString GetLearnmapsToTransfer(int iLicenseId) {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferRequestBody();
            inValue.Body.iLicenseId = iLicenseId;
            SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferResponse retVal = ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetLearnmapsToTransfer(inValue);
            return retVal.Body.GetLearnmapsToTransferResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferResponse> SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap.GetLearnmapsToTransferAsync(SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferRequest request) {
            return base.Channel.GetLearnmapsToTransferAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferResponse> GetLearnmapsToTransferAsync(int iLicenseId) {
            SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferRequest inValue = new SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferRequest();
            inValue.Body = new SoftObject.TrainConcept.TCLocalServiceReference1.GetLearnmapsToTransferRequestBody();
            inValue.Body.iLicenseId = iLicenseId;
            return ((SoftObject.TrainConcept.TCLocalServiceReference1.QueryUpdateSoap)(this)).GetLearnmapsToTransferAsync(inValue);
        }
    }
}
